services:
  - type: web
    name: fayezchat
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --workers 1 --threads 4 --timeout 0 --bind 0.0.0.0:$PORT"
    envVars:
      - key: ULTRAMSG_INSTANCE_ID
        sync: false
      - key: ULTRAMSG_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
    autoDeploy: false  # اقتراح: لتجنب الانتشار التلقائي غير المدروس
